pipelines:
  default:
    - step:
        image: firstinversion/build_environment:gcc-8
        script:
          - CONAN_RUN_TEST=True conan create . firstinversion/testing
        services:
          - postgres
  tags:
    '*':
      - step:
          image: firstinversion/build_environment:gcc-8
          script:
            - CONAN_RUN_TEST=True conan create . firstinversion/testing
            - conan test conan_test async_pqxx/$BITBUCKET_TAG@firstinversion/testing
            - conan user $CONAN_USER -r firstinversion -p $CONAN_PASSWORD
            - conan upload async_pqxx/$BITBUCKET_TAG@firstinversion/testing --all -r=firstinversion
          services:
            - postgres

definitions:
  services:
    postgres:
      image: postgres
      variables:
        POSTGRES_DB: 'postgres'
        POSTGRES_USER: 'test_user'
        POSTGRES_PASSWORD: 'test_user_password'
